# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ten0s/centos6.5_x86_64"
  config.vm.synced_folder "rpms", "/shared"

  config.vbguest.auto_update = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "build.yml"
    ansible.extra_vars = {
      kernel_version: "2.6.32-504.16.2.el6",
      drbd_version: {major: 8, minor: 4, patch: 4}
    }
  end
end
