---
- hosts: all
  sudo: true
  vars:
  - erlang_version: R16B03-6
  - rabbitmq_version: 3.4.1
  - rabbitmq_username: alley
  - rabbitmq_password: alley
  - mongodb_version: 2.6.5

  roles:
  - {role: common}

  tasks:
  - include: tasks/erlang.yml
  - include: tasks/rabbitmq.yml
