---
- hosts: all
  sudo: true
  vars:
  - erlang_version: R16B03-6
  - rabbitmq_version: 3.4.1
  - rabbitmq_username: alley
  - rabbitmq_password: alley
  - mongodb_version: 2.6.5

  handlers:
    - name: Restart MongoDB
      service: name=mongod state=restarted

  roles:
  - {role: common, tags: ["common"]}

  tasks:
  - {include: tasks/erlang.yml, tags: ["erlang"]}
  - {include: tasks/rabbitmq.yml, tags: ["rabbitmq"]}
  - {include: tasks/mongodb.yml, tags: ["mongodb"]}
