# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ten0s/centos6.5_x86_64"
  config.vm.network "forwarded_port", guest: 22, host: 2405
  config.vm.network "public_network", bridge: "eth0"

  #config.vm.network "forwarded_port", guest: 27017, host: 27017
  #config.vm.network "forwarded_port", guest: 5672, host: 5672
  #config.vm.network "forwarded_port", guest: 8001, host: 8001
  #config.vm.network "forwarded_port", guest: 8002, host: 8002
  #config.vm.network "forwarded_port", guest: 8071, host: 8071

  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
end
