- name: Import Erlang Solutions GPG key
  rpm_key: key=http://packages.erlang-solutions.com/rpm/erlang_solutions.asc
           state=present

- name: Add Erlang Solution repo
  copy: src=files/erlang_solutions.repo
        dest=/etc/yum.repos.d/
        owner=root
        group=root
        mode=0644

- name: Install Erlang
  yum: name=esl-erlang-{{erlang_version}}
       state=present
