- name: Import RabbitMQ GPG key
  rpm_key: key=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
           state=present

- name: Register RabbitMQ version
  command: rpm -q rabbitmq-server
  register: rmq
  changed_when: false
  failed_when: false

- name: Download RabbitMQ
  get_url: url=https://www.rabbitmq.com/releases/rabbitmq-server/v{{rabbitmq_version}}/rabbitmq-server-{{rabbitmq_version}}-1.noarch.rpm
           dest=/tmp/
  when: rmq.stdout.find('{{rabbitmq_version}}') == -1

- name: Install RabbitMQ
  command: rpm -Uv --nodeps /tmp/rabbitmq-server-{{rabbitmq_version}}-1.noarch.rpm
  when: rmq.stdout.find('{{rabbitmq_version}}') == -1

- name: Enable RabbitMQ Management plugin
  rabbitmq_plugin: names=rabbitmq_management
                   state=enabled

- name: Copy RabbitMQ Management CLI
  copy: src=files/rabbitmqadmin-{{rabbitmq_version}}
        dest=/usr/sbin/rabbitmqadmin
        mode=0755

- name: Start RabbitMQ
  command: rabbitmq-server -detached
  failed_when: false

- name: Wait for RabbitMQ
  wait_for: port=15672

- name: Add RabbitMQ user
  rabbitmq_user: user={{rabbitmq_username}}
                 password={{rabbitmq_password}}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 tags=administrator
                 state=present

- name: Delete default RabbitMQ user
  rabbitmq_user: user=guest
                 state=absent

- name: Stop RabbitMQ
  command: rabbitmqctl stop
