- name: Install Supervisord
  pip: name=supervisor
       state=present

- name: Create Supervisord's config dir
  file: path={{item.path}} state=directory
        owner={{item.owner}} group={{item.group}}
  with_items:
  - {path: /etc/supervisor.d,
     owner: root,
     group: root}
  - {path: /opt/bin,
     owner: root,
     group: root}
  - {path: /var/log/pmm,
     owner: bms,
     group: bms}

- name: Copy configuration
  copy: src={{item.src}}
        dest={{item.dest}}
        mode={{item.mode}}
  with_items:
  - {src: files/etc/supervisord.conf,
     dest: /etc/supervisord.conf,
     mode: 644}
  - {src: files/etc/supervisor.d/poweralleyui.conf,
     dest: /etc/supervisor.d/poweralleyui.conf,
     mode: 644}
  - {src: files/etc/init.d/supervisord,
     dest: /etc/init.d/supervisord,
     mode: 755}
  - {src: files/opt/bin/poweralleyui.sh,
     dest: /opt/bin/poweralleyui.sh,
     mode: 755}

- name: Enable supervisord service
  service: name=supervisord
           state=restarted
           enabled=true
