- name: Install MySQL playbook's deps
  yum: name={{item}} state=latest
  with_items:
  - MySQL-python

- name: Install MySQL
  yum: name=mysql-server-5.1.73
       state=present

- name: Copy MySQL configuration
  copy: src=files/etc/my.cnf
        dest=/etc/my.cnf

- name: Enable MySQL service
  service: name=mysqld
           enabled=true
           state=started

- name: Create DB
  mysql_db: name={{poweralleyui_db_database}}
            state=present
  notify: Restart MySQL

- name: Setup DB priviledges
  mysql_user: name={{poweralleyui_db_username}}
              host={{item}}
              password={{poweralleyui_db_password}}
              priv=*.*:ALL,GRANT
              state=present
  mysql_user: name={{poweralleyui_db_username}}
              host={{item}}
              password={{poweralleyui_db_password}}
              priv=*.*:ALL,GRANT
              state=present
  with_items:
  - localhost
  - '%'
  notify: Restart MySQL
