- name: Install Nginx
  yum: name=nginx-1.0.15
       state=present

- name: Enable Nginx service
  service: name=nginx
           enabled=true
           state=started

- name: Copy Nginx configuration
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
  - {src: files/etc/nginx/nginx.conf,
     dest: /etc/nginx/nginx.conf}
  - {src: files/etc/nginx/fastcgi_params,
     dest: /etc/nginx/fastcgi_params}
  notify: Restart Nginx

- name: Create server.conf from template
  template: src=files/etc/nginx/conf.d/server.conf dest=/etc/nginx/conf.d/server.conf
  notify: Restart Nginx
