---
- name: Add PMM-BankAudi repo
  copy: src=files/etc/yum.repos.d/pmm-bankaudi.repo
        dest=/etc/yum.repos.d/pmm-bankaudi.repo
        mode=644

- name: Add PMM-BankAudi Rel repo list
  copy: src=files/etc/yum.repos.d/pmm-bankaudi-rel.list
        dest=/etc/yum.repos.d/pmm-bankaudi-rel.list

- name: Add PMM-BankAudi Dev repo list
  copy: src=files/etc/yum.repos.d/pmm-bankaudi-dev.list
        dest=/etc/yum.repos.d/pmm-bankaudi-dev.list
        mode=644

- name: Install PowerAlleyUI
  yum: name=pmm-bms-poweralleyui-bankaudi-{{poweralleyui_version}}
       state=installed
  notify: Restart Supervisord

- name: Provision Web.config
  template: src=files/Web.config.j2
            dest=/opt/poweralleyui-{{poweralleyui_version}}/Web.config
  notify: Restart Supervisord

- name: Ensure correct rights
  file: path=/opt/poweralleyui-{{poweralleyui_version}}
        owner={{run_user}}
        group={{run_user}}
        recurse=true
        follow=true
  notify: Restart Supervisord

- name: Ensure link exists
  file: src=/opt/poweralleyui-{{poweralleyui_version}}
        dest=/opt/poweralleyui
        state=link
  notify: Restart Supervisord
