# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-6.5-i386"
  config.vm.network "forwarded_port", guest: 22, host: 2402

  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end

  config.vbguest.auto_update = false

  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "inventory"
    ansible.playbook = "../ansible-playbooks/upgrade_guest_additions.yml"
    ansible.extra_vars = {
      vbox_version: "4.3.28",
      vbox_ssh_port: 2402
    }
  end
end
